/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import entidades.Ciudad;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author crist
 */
public class Ciudades extends javax.swing.JInternalFrame {

    /**
     * Creates new form Ciudades
     */
    private DefaultComboBoxModel  modeloCombo=new DefaultComboBoxModel(){
        
     public boolean isCellEditable(int c, int f){
            return false;
        }
    };

    private DefaultTableModel modeloTabla=new DefaultTableModel(){
        
     public boolean isCellEditable(int c, int f){
            return false;
        }
    };
    public Ciudades() {
        initComponents();
        armarCabecera();
        
        cargarComboTipoBusqueda();
        JCBtipoBusqueda.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JRBactivos = new javax.swing.JRadioButton();
        JTFid = new javax.swing.JTextField();
        JLid = new javax.swing.JLabel();
        JLtitulo = new javax.swing.JLabel();
        JLbuscar = new javax.swing.JLabel();
        JCBtipoBusqueda = new javax.swing.JComboBox<>();
        JLobjetos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTalojamiento = new javax.swing.JTable();
        JBsalir = new javax.swing.JButton();
        JRBtodos = new javax.swing.JRadioButton();
        JTFbuscar = new javax.swing.JTextField();

        JRBactivos.setText("Activos");
        JRBactivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRBactivosActionPerformed(evt);
            }
        });

        JTFid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFidActionPerformed(evt);
            }
        });

        JLid.setText("ID:");

        JLtitulo.setText("Busqueda de Alojamientos");

        JLbuscar.setText("Buscar segun:");

        JCBtipoBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBtipoBusquedaActionPerformed(evt);
            }
        });

        JTalojamiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(JTalojamiento);

        JBsalir.setText("Salir");
        JBsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBsalirActionPerformed(evt);
            }
        });

        JRBtodos.setText("Todos");
        JRBtodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRBtodosActionPerformed(evt);
            }
        });

        JTFbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JTFbuscarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(JBsalir)
                                .addGap(34, 34, 34)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(JLtitulo)
                        .addGap(306, 306, 306))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JLbuscar)
                                .addGap(42, 42, 42)
                                .addComponent(JCBtipoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(JLid)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(JTFid, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(JLobjetos, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(JTFbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(JRBtodos)
                                    .addGap(207, 207, 207)
                                    .addComponent(JRBactivos))))
                        .addGap(169, 169, 169))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLtitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLbuscar)
                            .addComponent(JCBtipoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTFbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(JLobjetos, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTFid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLid))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JRBtodos)
                    .addComponent(JRBactivos))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JBsalir)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JRBactivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRBactivosActionPerformed
        // TODO add your handling code here:
        if(JRBactivos.isSelected()){
            JRBtodos.setSelected(false);
        }else{
            JRBtodos.setSelected(true);
        }
        limpiarTabla();
        cargarCiudades();
    }//GEN-LAST:event_JRBactivosActionPerformed

    private void JTFidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFidActionPerformed
        //        // TODO add your handling code here:
        try{
            int id=Integer.parseInt(JTFid.getText());
            limpiarTabla();
            cargarCiudades();
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null, "Ingrese solo numeros enteros");
        }
    }//GEN-LAST:event_JTFidActionPerformed

    private void JCBtipoBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBtipoBusquedaActionPerformed
        // TODO add your handling code here:
        JRBactivos.setEnabled(true);
        JTFid.setText("");
        switch (JCBtipoBusqueda.getSelectedIndex()) {
            case 0:
            JLobjetos.setVisible(false);
            JTFbuscar.setVisible(false);
            JLid.setVisible(false);
            JTFid.setEnabled(false);
            JTFid.setVisible(false);

            limpiarTabla();
            cargarCiudades();
            break;
            case 1:
            JLobjetos.setVisible(false);
            JTFbuscar.setVisible(false);
            JLid.setVisible(true);
            JTFid.setEnabled(true);
            JTFid.setVisible(true);
            JRBactivos.setEnabled(false);
            break;
            case 2:
            JLid.setVisible(false);
            JTFid.setEnabled(false);
            JTFid.setVisible(false);
            JTFbuscar.setVisible(true);
            JLobjetos.setText("Ciudad:");
            JLobjetos.setVisible(true);
            
            limpiarTabla();
            cargarCiudades();
            break;
            case 3:
            JLid.setVisible(false);
            JTFid.setEnabled(false);
            JTFid.setVisible(false);
            JTFbuscar.setVisible(true);
            JLobjetos.setText("Provincia:");
            JLobjetos.setVisible(true);
            
            limpiarTabla();
            cargarCiudades();
            break;
            case 4:
            JLid.setVisible(false);
            JTFid.setEnabled(false);
            JTFid.setVisible(false);
            JTFbuscar.setVisible(true);
            JLobjetos.setText("Pais:");
            JLobjetos.setVisible(true);
            
            limpiarTabla();
            cargarCiudades();
            break;
        }
        JRBtodos.setSelected(true);
        JRBactivos.setSelected(false);
    }//GEN-LAST:event_JCBtipoBusquedaActionPerformed

    private void JBsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBsalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_JBsalirActionPerformed

    private void JRBtodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRBtodosActionPerformed
        // TODO add your handling code here:
        if(JRBtodos.isSelected()){
            JRBactivos.setSelected(false);
        }else{
            JRBactivos.setSelected(true);
        }
        limpiarTabla();
        cargarCiudades();
    }//GEN-LAST:event_JRBtodosActionPerformed

    private void JTFbuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFbuscarKeyReleased
        // TODO add your handling code here:
        if(JRBtodos.isSelected()){
            JRBactivos.setSelected(false);
        }else{
            JRBactivos.setSelected(true);
        }
        limpiarTabla();
        cargarCiudades();
    }//GEN-LAST:event_JTFbuscarKeyReleased
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBsalir;
    private javax.swing.JComboBox<String> JCBtipoBusqueda;
    private javax.swing.JLabel JLbuscar;
    private javax.swing.JLabel JLid;
    private javax.swing.JLabel JLobjetos;
    private javax.swing.JLabel JLtitulo;
    private javax.swing.JRadioButton JRBactivos;
    private javax.swing.JRadioButton JRBtodos;
    private javax.swing.JTextField JTFbuscar;
    private javax.swing.JTextField JTFid;
    private javax.swing.JTable JTalojamiento;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    private void armarCabecera() {
        modeloTabla.addColumn("Id");
        modeloTabla.addColumn("Nombre");
        modeloTabla.addColumn("Provincia");
        modeloTabla.addColumn("Pais");
        modeloTabla.addColumn("Estado");
        JTalojamiento.setModel(modeloTabla);
    }
    private void limpiarTabla() {
        int f = JTalojamiento.getRowCount() - 1;
        for (; f >= 0; f--) {
            modeloTabla.removeRow(f);
        }
    }
    private void cargarCiudades() {
        JTalojamiento.clearSelection();
        
        List<Ciudad> ciudades=new ArrayList();
        int opcion;
        try {
            switch (JCBtipoBusqueda.getSelectedIndex()) {
                case 0:
                    if (JRBtodos.isSelected()) {
                        opcion = 1;
                    } else {
                        opcion = 0;
                    }
                    ciudades = Menu.ciudadData.listarCiudades(opcion);
                    break;
                case 1:
                    try {
                        int id = Integer.parseInt(JTFid.getText());
                        ciudades.add(Menu.ciudadData.buscarCiudadPorId(id));
                    } catch (NumberFormatException ex) {

                    }

                    break;
                case 2:
                    if (JRBtodos.isSelected()) {
                        opcion = 1;
                    } else {
                        opcion = 0;
                    }
                    modeloTabla.setRowCount(0);
                    for(Ciudad ciu:Menu.ciudadData.listarCiudades(opcion)){
                        if(ciu.getNombre().startsWith(JTFbuscar.getText())){
                            modeloTabla.addRow(new Object[]{
                                ciu.getIdCiudad(),
                                ciu.getNombre(),
                                
                                ciu.getProvincia(),
                                ciu.getPais(),
                                ciu.isActivo()
                            }); 
                        }
                    }
                    break;
                case 3:
                    if (JRBtodos.isSelected()) {
                        opcion = 1;
                    } else {
                        opcion = 0;
                    }
                    modeloTabla.setRowCount(0);
                    for(Ciudad ciu:Menu.ciudadData.listarCiudades(opcion)){
                        if(ciu.getProvincia().startsWith(JTFbuscar.getText())){
                            modeloTabla.addRow(new Object[]{
                                ciu.getIdCiudad(),
                                ciu.getNombre(),
                                
                                ciu.getProvincia(),
                                ciu.getPais(),
                                ciu.isActivo()
                            }); 
                        }
                    }
                    break;
                case 4:
                    if (JRBtodos.isSelected()) {
                        opcion = 1;
                    } else {
                        opcion = 0;
                    }
                    modeloTabla.setRowCount(0);
                    for(Ciudad ciu:Menu.ciudadData.listarCiudades(opcion)){
                        if(ciu.getPais().startsWith(JTFbuscar.getText())){
                            modeloTabla.addRow(new Object[]{
                                ciu.getIdCiudad(),
                                ciu.getNombre(),
                                
                                ciu.getProvincia(),
                                ciu.getPais(),
                                ciu.isActivo()
                            }); 
                        }
                    }
                    break;   
            }
        }catch(NullPointerException ex){
            
        }
        
        
        try {
            for (Ciudad ciu : ciudades) {
                ciu.toString();
                modeloTabla.addRow(new Object[]{
                    
                    ciu.getIdCiudad(),
                    ciu.getNombre(),
                    ciu.getProvincia(),
                    ciu.getPais(),                    
                    ciu.isActivo()
                });
            }
        } catch (Exception ex) {
            
        }
    }
    private void cargarComboTipoBusqueda(){
     JCBtipoBusqueda.addItem("Todos");
     JCBtipoBusqueda.addItem("ID");
     JCBtipoBusqueda.addItem("Ciudad");
     JCBtipoBusqueda.addItem("Provincia");
     JCBtipoBusqueda.addItem("Pais");
          
    }
}
